import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import {
  BetModel,
  OmitAutoGeneratedColumns,
  PlayerModel,
} from '../../shared/util/supabase-types';
import { BetComponent } from '../../shared/ui/bet.component';

export const confirmPlaceBetDialogKey = 'confirm-place-bet';

@Component({
  selector: 'joshies-confirm-place-bet-dialog',
  imports: [ConfirmDialogModule, BetComponent],
  template: `
    <p-confirm-dialog styleClass="mx-4" [key]="confirmPlaceBetDialogKey">
      <ng-template #message let-message>
        <div>
          <!-- Prompt -->
          <p class="mb-6">Do you want to submit this bet request?</p>

          <!-- Bet Preview -->
          <joshies-bet [bet]="bet()" [userPlayerId]="userPlayerId()" />
        </div>
      </ng-template>
    </p-confirm-dialog>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ConfirmPlaceBetDialogComponent {
  readonly bet = input.required<OmitAutoGeneratedColumns<BetModel>>();
  readonly userPlayerId = input.required<PlayerModel['id']>();

  protected readonly confirmPlaceBetDialogKey = confirmPlaceBetDialogKey;
}
