import { inject, Injectable, Signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { PostgrestSingleResponse, SupabaseClient } from '@supabase/supabase-js';
import { MessageService } from 'primeng/api';
import {
  combineLatestWith,
  distinctUntilChanged,
  map,
  Observable,
  of,
  shareReplay,
  switchMap,
} from 'rxjs';
import { teamsWithParticipantInfo } from '../util/event-helpers';
import { resizeImage } from '../util/image-helpers';
import { whenAllValuesNotNull, whenNotNull } from '../util/rxjs-helpers';
import { Database } from '../util/schema';
import {
  Function,
  realtimeUpdatesFromTable,
  RoundPhase,
  showMessageOnError,
  StorageBucket,
  Table,
} from '../util/supabase-helpers';
import {
  BracketModel,
  EventModel,
  EventParticipantModel,
  EventTeamModel,
  OmitAutoGeneratedColumns,
} from '../util/supabase-types';
import { GameStateService } from './game-state.service';
import { PlayerService } from './player.service';

export interface EventParticipantWithPlayerInfo {
  participant_id: number;
  team_id: number;
  player_id: number;
  display_name: string;
  avatar_url: string;
  score: number;
}

export interface EventTeamWithParticipantInfo extends EventTeamModel {
  participants: EventParticipantWithPlayerInfo[];
}

@Injectable({
  providedIn: 'root',
})
export class EventService {
  private readonly supabase: SupabaseClient<Database> = inject(SupabaseClient);
  private readonly gameStateService = inject(GameStateService);
  private readonly messageService = inject(MessageService);
  private readonly playerService = inject(PlayerService);

  readonly events$: Observable<EventModel[]> =
    this.gameStateService.sessionId$.pipe(
      switchMap((sessionId) =>
        realtimeUpdatesFromTable(
          this.supabase,
          Table.Event,
          `session_id=eq.${sessionId}`,
        ).pipe(
          map((events) =>
            events.sort((a, b) => a.round_number - b.round_number),
          ),
        ),
      ),
      shareReplay(1),
    );

  readonly eventForThisRound$: Observable<EventModel | null> =
    this.gameStateService.roundNumber$.pipe(
      switchMap((roundNumber) =>
        this.events$.pipe(
          map(
            (events) =>
              events?.find((event) => event.round_number === roundNumber) ??
              null,
          ),
        ),
      ),
      shareReplay(1),
    );

  readonly eventForThisRound = toSignal(this.eventForThisRound$);

  readonly eventForNextRound$: Observable<EventModel | null> =
    this.gameStateService.roundNumber$.pipe(
      switchMap((roundNumber) =>
        this.events$.pipe(
          map(
            (events) =>
              events?.find((event) => event.round_number === roundNumber + 1) ??
              null,
          ),
        ),
      ),
      shareReplay(1),
    );

  readonly eventForNextRound = toSignal(this.eventForNextRound$);

  readonly events = toSignal(this.events$);

  readonly eventTeams$: Observable<EventTeamModel[] | null> = this.events$.pipe(
    map((events) => events?.map((ev) => ev.id) ?? null),
    whenNotNull((eventIds) =>
      realtimeUpdatesFromTable(
        this.supabase,
        Table.EventTeam,
        `event_id=in.(${eventIds})`,
      ),
    ),
    shareReplay(1),
  );

  readonly eventTeams = toSignal(this.eventTeams$);

  readonly eventParticipants$: Observable<EventParticipantModel[] | null> =
    this.eventTeams$.pipe(
      map((eventTeams) => eventTeams?.map((eventTeam) => eventTeam.id) ?? null),
      whenNotNull((eventTeamIds) =>
        realtimeUpdatesFromTable(
          this.supabase,
          Table.EventParticipant,
          `team_id=in.(${eventTeamIds})`,
        ),
      ),
      shareReplay(1),
    );

  readonly eventParticipants = toSignal(this.eventParticipants$);

  readonly eventParticipantsWithPlayerInfo$: Observable<
    EventParticipantWithPlayerInfo[] | null
  > = this.eventParticipants$.pipe(
    combineLatestWith(this.playerService.players$),
    map(([participants, players]) => ({ participants, players })),
    whenAllValuesNotNull(({ participants, players }) =>
      of(
        participants.map((participant) => {
          const player = players.find(
            (p) => p.player_id === participant.player_id,
          )!;

          return {
            participant_id: participant.id,
            team_id: participant.team_id,
            player_id: participant.player_id,
            display_name: player.display_name,
            avatar_url: player.avatar_url,
            score: player.score,
          };
        }),
      ),
    ),
    shareReplay(1),
  );

  readonly eventParticipantsWithPlayerInfo: Signal<
    EventParticipantWithPlayerInfo[] | null | undefined
  > = toSignal(this.eventParticipantsWithPlayerInfo$);

  readonly eventTeamRoundScores$ = this.eventTeams$.pipe(
    whenNotNull((eventTeams) =>
      of(eventTeams.map((team) => team.id)).pipe(
        distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b)),
        switchMap((teamIds) =>
          realtimeUpdatesFromTable(
            this.supabase,
            Table.EventTeamRoundScore,
            `team_id=in.(${teamIds})`,
          ),
        ),
      ),
    ),
    shareReplay(1),
  );

  readonly eventTeamRoundScores = toSignal(this.eventTeamRoundScores$);

  readonly eventTeamsWithParticipantInfo$: Observable<
    EventTeamWithParticipantInfo[]
  > = this.eventTeams$.pipe(
    combineLatestWith(this.eventParticipantsWithPlayerInfo$),
    map(([teams, participants]) =>
      teamsWithParticipantInfo(teams ?? [], participants ?? []),
    ),
  );

  readonly eventTeamsWithParticipantInfo = toSignal(
    this.eventTeamsWithParticipantInfo$,
    { initialValue: [] },
  );

  readonly brackets$: Observable<OmitAutoGeneratedColumns<BracketModel[]>> =
    this.events$.pipe(
      switchMap((events) =>
        events
          ? of(events.map((event) => event.id)).pipe(
              distinctUntilChanged(
                (a, b) => JSON.stringify(a) === JSON.stringify(b),
              ),
              switchMap((eventIds) =>
                realtimeUpdatesFromTable(
                  this.supabase,
                  Table.Bracket,
                  `event_id=in.(${eventIds})`,
                ),
              ),
            )
          : of([]),
      ),
      shareReplay(1),
    );

  readonly brackets = toSignal(this.brackets$);

  async createEvent(
    event: OmitAutoGeneratedColumns<EventModel>,
  ): Promise<PostgrestSingleResponse<null>> {
    return this.supabase.from(Table.Event).insert(event);
  }

  async updateEvent(
    eventId: number,
    partialEvent: Partial<OmitAutoGeneratedColumns<EventModel>>,
  ): Promise<PostgrestSingleResponse<null>> {
    return this.supabase
      .from(Table.Event)
      .update(partialEvent)
      .eq('id', eventId);
  }

  async deleteEvent(eventId: number): Promise<PostgrestSingleResponse<null>> {
    return this.supabase.from(Table.Event).delete().eq('id', eventId);
  }

  async reorderEvents(
    eventsWithNewRoundNumber: Record<number, number>,
  ): Promise<PostgrestSingleResponse<undefined>> {
    return this.supabase.rpc(Function.ReorderEvents, {
      events_with_new_round_number: eventsWithNewRoundNumber,
    });
  }

  //Upload a given image to supabase. Return its new address to be displayed & saved
  async uploadImage(image: File): Promise<string> {
    const resizedImage = await resizeImage(image, 200);
    const uploadPath = `events/${Date.now()}.webp`;

    const { data: uploadData, error: uploadError } = await showMessageOnError(
      this.supabase.storage
        .from(StorageBucket.EventImages)
        .upload(uploadPath, resizedImage),
      this.messageService,
    );

    if (uploadError) {
      return '';
    }

    return this.supabase.storage
      .from(StorageBucket.EventImages)
      .getPublicUrl(uploadData.path).data.publicUrl;
  }

  async createEventTeam(
    team: OmitAutoGeneratedColumns<EventTeamModel>,
  ): Promise<PostgrestSingleResponse<EventTeamModel[]>> {
    return this.supabase.from(Table.EventTeam).insert(team).select();
  }

  async deleteEventTeamAndUpdateSeeds(
    teamId: number,
    seedUpdates: { id: number; seed: number }[],
  ): Promise<PostgrestSingleResponse<undefined>> {
    return this.supabase.rpc(Function.DeleteEventTeamAndUpdateSeeds, {
      team_id: teamId,
      seed_updates: seedUpdates,
    });
  }

  async batchUpdateEventTeamSeeds(
    updates: Pick<EventTeamModel, 'id' | 'seed'>[],
  ): Promise<PostgrestSingleResponse<undefined>> {
    return this.supabase.rpc(Function.UpdateEventTeamSeeds, {
      updates,
    });
  }

  async createEventParticipant(
    participant: OmitAutoGeneratedColumns<EventParticipantModel>,
  ): Promise<PostgrestSingleResponse<EventParticipantModel[]>> {
    return this.supabase
      .from(Table.EventParticipant)
      .insert(participant)
      .select();
  }

  async updateEventParticipant(
    participantId: EventParticipantModel['id'],
    participant: Partial<OmitAutoGeneratedColumns<EventParticipantModel>>,
  ): Promise<PostgrestSingleResponse<EventParticipantModel[]>> {
    return this.supabase
      .from(Table.EventParticipant)
      .update(participant)
      .eq('id', participantId)
      .select();
  }

  async deleteEventParticipant(
    participantId: EventParticipantModel['id'],
  ): Promise<PostgrestSingleResponse<null>> {
    return this.supabase
      .from(Table.EventParticipant)
      .delete()
      .eq('id', participantId);
  }

  async submitEventScores(teamScores: TeamScores) {
    return this.supabase.rpc(Function.SubmitEventScores, {
      team_scores: teamScores,
    });
  }

  getTeamsByRound(
    eventId: EventModel['id'] | undefined,
    brackets: OmitAutoGeneratedColumns<BracketModel>[] | undefined,
  ) {
    if (!eventId || !brackets) {
      return [];
    }
    const bracketArr = brackets.filter(
      (bracket) => bracket.event_id === eventId,
    );
    const teamsByRoundString =
      (bracketArr && bracketArr.length > 0 ? bracketArr[0].data : null) ?? '[]';
    return (JSON.parse(teamsByRoundString) ?? []) as number[][];
  }

  async saveTournamentState(
    eventId: EventModel['id'],
    teamsByRound: number[][],
  ) {
    return this.supabase
      .from(Table.Bracket)
      .upsert(
        { event_id: eventId, data: JSON.stringify(teamsByRound) },
        { onConflict: 'event_id' },
      )
      .select();
  }

  async submitTournamentResults(
    eventId: EventModel['id'],
    teamsByRound: number[][],
  ) {
    const response = await this.saveTournamentState(eventId, teamsByRound);
    if (response.error) {
      return response;
    }

    return this.gameStateService.setRoundPhase(RoundPhase.WaitingForNextRound);
  }
}

export type TeamScores = {
  team_id: EventTeamModel['id'];
  score: number;
  position: number;
}[];
