-- Prizes feature
--
-- Adds:
--   * prize-images storage bucket (public read for image display)
--   * player.prize_tokens int counter
--   * session.prize_token_on_event_win boolean (auto-trigger toggle)
--   * prize table (1-of-1 per session, owned by zero or one player)
--   * spin_prize_machine() RPC
--   * end_round() updated to mint tokens for 1st place team participants when toggle is on


-- ============================================================================
-- 1. Storage bucket
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('prize-images', 'prize-images', true)
on conflict (id) do nothing;

create policy "Authenticated users can read prize-images"
on storage.objects for select to authenticated
using (bucket_id = 'prize-images');

create policy "Authenticated users can upload prize-images"
on storage.objects for insert to authenticated
with check (bucket_id = 'prize-images');

create policy "Authenticated users can update prize-images"
on storage.objects for update to authenticated
using (bucket_id = 'prize-images');

create policy "Authenticated users can delete prize-images"
on storage.objects for delete to authenticated
using (bucket_id = 'prize-images');


-- ============================================================================
-- 2. Column additions
-- ============================================================================

alter table "public"."player"
  add column "prize_tokens" integer not null default 0;

alter table "public"."player"
  add constraint "player_prize_tokens_nonnegative" check (prize_tokens >= 0);

alter table "public"."session"
  add column "prize_token_on_event_win" boolean not null default true;


-- ============================================================================
-- 3. Prize table
-- ============================================================================

create table "public"."prize" (
    "id" bigint generated by default as identity not null,
    "session_id" bigint not null,
    "image_url" text not null,
    "won_by_player_id" bigint,
    "won_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."prize" enable row level security;

create unique index prize_pkey on public.prize using btree (id);
create index prize_session_id_idx on public.prize using btree (session_id);
create index prize_won_by_player_id_idx on public.prize using btree (won_by_player_id);
create index prize_session_unwon_idx on public.prize using btree (session_id) where (won_by_player_id is null);

alter table "public"."prize"
  add constraint "prize_pkey" primary key using index "prize_pkey";

alter table "public"."prize"
  add constraint "prize_session_id_fkey"
  foreign key (session_id) references session(id)
  on update cascade on delete cascade
  not valid;
alter table "public"."prize" validate constraint "prize_session_id_fkey";

alter table "public"."prize"
  add constraint "prize_won_by_player_id_fkey"
  foreign key (won_by_player_id) references player(id)
  on update cascade on delete restrict
  not valid;
alter table "public"."prize" validate constraint "prize_won_by_player_id_fkey";

alter table "public"."prize"
  add constraint "prize_won_consistency"
  check ((won_by_player_id is null) = (won_at is null));

create policy "Enable all for authenticated users only"
on "public"."prize" as permissive for all
to authenticated
using (true);

grant delete, insert, references, select, trigger, truncate, update
  on table "public"."prize" to anon;
grant delete, insert, references, select, trigger, truncate, update
  on table "public"."prize" to authenticated;
grant delete, insert, references, select, trigger, truncate, update
  on table "public"."prize" to service_role;


-- ============================================================================
-- 4. spin_prize_machine RPC
-- ============================================================================

create or replace function public.spin_prize_machine(_player_id bigint)
 returns public.prize
 language plpgsql
as $function$
declare
    _session_id bigint;
    _tokens int;
    _selected_prize prize;
begin
    -- Lock player row so concurrent spins by the same player serialize
    select session_id, prize_tokens into _session_id, _tokens
    from public.player
    where id = _player_id
    for update;

    if _tokens is null then
        raise exception 'Player not found';
    end if;

    if _tokens <= 0 then
        raise exception 'No prize tokens available';
    end if;

    -- Pick a random un-won prize from this session, locking the row so concurrent
    -- spins by different players don't both pick the same prize
    select * into _selected_prize
    from public.prize
    where session_id = _session_id and won_by_player_id is null
    order by random()
    limit 1
    for update skip locked;

    if _selected_prize.id is null then
        raise exception 'Prize pool is empty';
    end if;

    update public.prize
    set won_by_player_id = _player_id,
        won_at = now(),
        updated_at = now()
    where id = _selected_prize.id
    returning * into _selected_prize;

    update public.player
    set prize_tokens = prize_tokens - 1,
        updated_at = now()
    where id = _player_id;

    return _selected_prize;
end;
$function$
;


-- ============================================================================
-- 5. end_round() update: mint tokens for 1st place team participants
--
-- 1st place is the team(s) with the maximum points awarded this round (per
-- team_score_changes). Ties at the max all get tokens. Disabled players are
-- excluded from token minting. Existing transaction + player_round_score
-- behavior is unchanged. Return type changes from void to jsonb so the caller
-- can fire push notifications to token recipients.
-- ============================================================================

drop function if exists public.end_round(integer, jsonb);

create function public.end_round(_round_number integer, team_score_changes jsonb)
 returns jsonb
 language plpgsql
as $function$
declare
    event_team_id int8;
    points int8;
    team_player_id int8;
    event_name text;
    _session_id int8;
    _auto_mint boolean;
    _max_points int8;
    _token_recipient_user_ids uuid[] := '{}';
    _affected int;
begin
    select session_id into _session_id from game_state where id = 1;

    select name into event_name from event
    where session_id = _session_id and round_number = _round_number;

    select prize_token_on_event_win into _auto_mint
    from session where id = _session_id;

    select max((value)::int8) into _max_points
    from jsonb_each_text(team_score_changes) as t(key, value);

    for event_team_id, points in select * from jsonb_each_text(team_score_changes) loop
        for team_player_id in
            select player_id from event_participant where team_id = event_team_id
        loop
            -- existing: transaction + round-score snapshot
            insert into public.transaction (player_id, num_points, description)
            values (team_player_id, points, 'Points earned from ' || event_name);

            insert into public.player_round_score (player_id, round_number, score)
            values (team_player_id, _round_number,
                (select score from public.player where id = team_player_id)
            );

            -- new: mint prize token for 1st place enabled players
            if _auto_mint and points = _max_points and points > 0 then
                update public.player
                set prize_tokens = prize_tokens + 1,
                    updated_at = now()
                where id = team_player_id and enabled = true;
                get diagnostics _affected = row_count;
                if _affected > 0 then
                    _token_recipient_user_ids := _token_recipient_user_ids ||
                        (select user_id from public.player where id = team_player_id);
                end if;
            end if;
        end loop;
    end loop;

    update public.game_state
    set round_phase = 'waiting_for_next_round'
    where id = 1;

    return jsonb_build_object('token_recipient_user_ids', _token_recipient_user_ids);
end;
$function$
;
